version: "3"

services:
  rabbit:
    container_name: rabbit_container
    image: rabbitmq:3-management
    hostname: rabbitmq_jsnsoftware
    ports:
      - "5672:5672"
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=mqadmin
      - RABBITMQ_DEFAULT_PASS=mqadmin